uploads = []
generated = []

[[outputs]]
id = "dwN9QPxwpoZQjcHegCHcv"
uri = "file://AI-SNIPER-PRO-MAX-FINAL.tar.gz"
type = "unspecified"
title = "AI SNIPER PRO MAX — نهائي مع فلترة الأزواج الديناميكية"
